-- Run from the workspace root with lua55.exe; no game or deployed files required.
local root = "mods/active/AnotherScoreboard/scripts/mods/AnotherScoreboard/"
local registered = {}
Utf8 = { upper = string.upper }
local function provider(name)
    local owner = { name = name, enabled = true }
    function owner:get_name() return self.name end
    function owner:is_enabled() return self.enabled end
    registered[name] = owner
    return owner
end
function get_mod(name) return registered[name] end
table.clear = function(t) for k in pairs(t) do t[k] = nil end end
local scoreboard = provider("AnotherScoreboard")
function scoreboard:original_require() return {} end
function scoreboard:io_dofile(path) return dofile(root .. path:match("([^/]+)$") .. ".lua") end
local External = dofile(root .. "AnotherScoreboard_external.lua")
scoreboard.external_stats = External
local Stats = dofile(root .. "AnotherScoreboard_stats.lua")
local a, b = provider("ProviderA"), provider("ProviderB")
local checks = 0
local function eq(actual, expected)
    checks = checks + 1
    assert(actual == expected, "check " .. checks .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual))
end
local function error_is(expected, fn, ...)
    local value, err = fn(...)
    eq(value, nil)
    eq(err, expected)
end
local function find(sections, key)
    for _, section in ipairs(sections) do
        for _, row in ipairs(section.rows) do if row.id == key then return row end end
    end
end
local gd = { id = "utility", label = "Provider utility", placement = "combat_utility" }
local group = assert(External.register_group(a, gd))
eq(group, "external:ProviderA:group:utility")
eq(External.register_group(a, gd), group)
local other_group = assert(External.register_group(b, gd))
eq(group ~= other_group, true)
error_is("invalid_owner", External.register_group, { get_name = function() return "ProviderA" end, is_enabled = function() return true end }, gd)
error_is("invalid_definition", External.register_group, a, { id = "x:y", label = "bad" })
error_is("invalid_placement", External.register_group, a, { id = "x", label = "bad", placement = "combat" })
error_is("invalid_definition", External.register_group, a, { id = "x", label = "bad", arbitrary = true })
error_is("definition_conflict", External.register_group, a, { id = "utility", label = "different" })
local sd = { id = "count", label = "Count", group = group, accumulation = "add", ranking = "higher_better", decimals = 2, suffix = " s" }
local key = assert(External.register_stat(a, sd))
error_is("invalid_group", External.register_stat, b, sd)
eq(External.get(key, "p1"), nil)
eq(External.update(key, "p1", 0), true)
eq(External.get(key, "p1"), 0)
eq(External.update(key, "p1", 1.25), true)
eq(External.update(key, "p1", 2), true)
eq(External.get(key, "p1"), 3.25)
eq(External.register_stat(a, sd), key)
eq(External.get(key, "p1"), 3.25)
local values = External.get(key)
values.p1 = 999
eq(External.get(key, "p1"), 3.25)
for _, value in ipairs({ math.huge, -math.huge, 0 / 0, "4", false, {} }) do
    error_is("invalid_value", External.update, key, "p1", value)
end
error_is("invalid_player_id", External.update, key, "", 1)
error_is("unknown_stat", External.update, "total_kills", "p1", 1)
error_is("invalid_format", External.register_stat, a, { id = "bad", label = "Bad", group = group, decimals = false })
error_is("invalid_definition", External.register_stat, a, { id = "bad", label = "Bad", group = group, ranking = false })
local tk = assert(External.register_stat(a, { id = "text", label = "Text", group = group, value_type = "text" }))
eq(External.update(tk, "p1", "Ready"), true)
eq(External.update(tk, "p1", "Finished"), true)
eq(External.get(tk, "p1"), "Finished")
eq(External.update(tk, "p2", ""), true)
eq(External.get(tk, "p2"), "")
error_is("invalid_value", External.update, tk, "p1", 1)
error_is("invalid_format", External.register_stat, a, { id = "bad", label = "Bad", group = group, value_type = "text", accumulation = "add" })
local low = assert(External.register_stat(a, { id = "low", label = "Low", group = group, ranking = "lower_better" }))
assert(External.update(low, "p1", 0))
assert(External.update(low, "p2", 5))
assert(External.update(low, "outsider", -10))
assert(External.update(key, "p2", 0))
Stats.init() -- Early registrations and values survive native initialization.
eq(External.get(key, "p1"), 3.25)
local ids = { p1 = true, p2 = true, missing = true }
Stats.ensure_entries(ids)
Stats.validate(ids)
local sections = Stats.sections()
eq(find(sections, key).values.missing, nil)
eq(find(sections, key).values.p1.best, true)
eq(find(sections, key).values.p2.worst, true)
eq(find(sections, low).values.p1.best, true)
eq(find(sections, low).values.outsider.best, false)
eq(find(sections, tk).ranked, false)
eq(External.format(find(sections, key), nil), "—")
eq(External.format(find(sections, key), 0), "0.00 s")
eq(External.format(find(sections, tk), "Finished"), "Finished")
local closed = External.filter(sections)
eq(find(closed, key), nil)
eq(find(closed, group).external_collapsed, true)
eq(find(External.filter(sections, { [group] = false }), key) ~= nil, true)
eq(find(External.filter(sections, nil, true), key) ~= nil, true)
local snapshot = Stats.snapshot_sections(ids, sections)
eq(find(snapshot, key).decimals, 2)
eq(find(snapshot, key).values.missing, nil)
eq(find(snapshot, key).values.p2.score, 0)
eq(find(snapshot, low).values.outsider.score, -10)
eq(find(snapshot, group).collapsed_by_default, true)
local own = assert(External.register_group(a, { id = "own", label = "Own category", collapsible = false }))
local own_stat = assert(External.register_stat(a, { id = "own", label = "Own row", group = own }))
eq(find(External.filter(Stats.sections()), own_stat) ~= nil, true)
local own_snapshot = Stats.snapshot_sections(ids)
eq(own_snapshot[#own_snapshot].category.label_text, "Own category")
eq(own_snapshot[#own_snapshot].category.uppercase, true)
local collected = 0
assert(External.set_collector(a, function(owner, api)
    eq(owner, a)
    eq(api, scoreboard)
    collected = collected + 1
    assert(External.update(key, "p1", 1))
    error("collector failure after publish")
end))
assert(External.set_collector(b, function() collected = collected + 1 end))
local errors = External.collect(scoreboard)
eq(collected, 2)
eq(type(errors.ProviderA), "string")
eq(errors.ProviderB, nil)
assert(External.set_collector(b, function()
    error(setmetatable({}, { __tostring = function() error("must not stringify this") end }))
end))
local non_string_errors = External.collect(scoreboard)
eq(non_string_errors.ProviderB, "collector raised a non-string error")
assert(External.set_collector(b, function() collected = collected + 1 end))
local captured = Stats.snapshot_sections(ids)
eq(find(captured, key).values.p1.score, 5.25)
a.enabled = false
error_is("provider_disabled", External.update, key, "p1", 1)
External.collect(scoreboard)
eq(collected, 4)
eq(find(Stats.sections(), key), nil)
a.enabled = true
local saved = Stats.export_active_run()
saved.external.stats[key].values.p1 = 8
eq(External.get(key, "p1"), 5.25)
Stats.clear()
eq(External.get(key, "p1"), nil)
eq(Stats.import_active_run(saved), true)
eq(External.get(key, "p1"), 8)
eq(External.unregister(a), true)
eq(find(Stats.sections(), key), nil)
eq(find(External.filter(snapshot, { [group] = false }), key).values.p1.score, 3.25)
eq(Stats.import_active_run(saved), true) -- Unknown provider data retained until late registration.
eq(Stats.export_active_run().external.stats[key].values.p1, 8)
eq(External.register_group(a, gd), group)
eq(External.register_stat(a, sd), key)
eq(External.get(key, "p1"), 8)
eq(External.register_stat(a, sd), key)
eq(External.get(key, "p1"), 8)
local malformed = { version = 1, stats = {}, external = { version = 1, stats = { [key] = { value_type = "number", values = { p1 = math.huge } } } } }
eq(Stats.import_active_run(malformed), false)
eq(External.get(key, "p1"), 8)
eq(Stats.import_active_run({ version = 1, stats = {} }), true)
eq(External.get(key, "p1"), nil)
eq(#External.filter({ { category = { key = "old" }, rows = { { id = "damage_dealt" } } } })[1].rows, 1)
assert(External.update(key, "p1", 0))
eq(Stats.has_active_run_data(), true)
Stats.clear()
eq(Stats.has_active_run_data(), false)
Stats.record("total_kills", "returning", 5)
Stats.ensure_entries({ other = true })
Stats.validate({ other = true })
Stats.ensure_entries({ returning = true })
eq(Stats.data_for("total_kills").returning.score, 5) -- Leaving the roster does not prune account totals.
Stats.clear()
Stats.record("total_kills", "p1", 5)
assert(Stats.rebaseline_diff("damage_taken", "p1", 100))
Stats.record("damage_taken", "p1", 120)
assert(External.update(key, "p1", 5))
tk = assert(External.register_stat(a, { id = "text", label = "Text", group = group, value_type = "text" }))
assert(External.update(tk, "p1", "saved"))
local merge_saved = Stats.export_active_run()
Stats.clear()
Stats.record("total_kills", "p1", 2)
assert(Stats.rebaseline_diff("damage_taken", "p1", 10))
Stats.record("damage_taken", "p1", 13)
assert(External.update(key, "p1", 2))
assert(External.update(tk, "p1", "live"))
eq(Stats.merge_active_run(merge_saved), true)
eq(Stats.data_for("total_kills").p1.score, 7)
eq(Stats.data_for("damage_taken").p1.score, 23)
eq(Stats.data_for("damage_taken").p1.value, 13)
eq(External.get(key, "p1"), 7)
eq(External.get(tk, "p1"), "live")
local before_bad_merge = Stats.data_for("total_kills").p1.score
eq(Stats.merge_active_run({ version = 1, stats = {}, external = { version = 1, stats = {
    [key] = { value_type = "number", values = { p1 = math.huge } },
} } }), false)
eq(Stats.data_for("total_kills").p1.score, before_bad_merge)
Stats.clear()
Stats.record("total_kills", "p1", 1e308)
local overflow_merge = Stats.export_active_run()
overflow_merge.external = { version = 1, stats = {} }
Stats.clear()
Stats.record("total_kills", "p1", 1e308)
eq(Stats.merge_active_run(overflow_merge), false)
eq(Stats.data_for("total_kills").p1.score, 1e308)
Stats.clear()
assert(External.update(key, "p1", 1e308))
error_is("invalid_value", External.update, key, "p1", 1e308)
eq(External.get(key, "p1"), 1e308)
eq(External.unregister(a), true)
eq(External.unregister(a), true)
local named_owner = provider("Provider: with spaces%")
local named_group = assert(External.register_group(named_owner, { id = "group", label = "Named provider" }))
local named_stat = assert(External.register_stat(named_owner, { id = "stat", label = "Named stat", group = named_group }))
eq(named_stat, "external:Provider%3A%20with%20spaces%25:stat:stat")
assert(External.update(named_stat, "p1", 12))
local named_saved = External.export()
eq(External.validate_snapshot(named_saved), true)
eq(External.unregister(named_owner), true)
eq(External.restore(named_saved), true)
eq(External.register_group(named_owner, { id = "group", label = "Named provider" }), named_group)
eq(External.register_stat(named_owner, { id = "stat", label = "Named stat", group = named_group }), named_stat)
eq(External.get(named_stat, "p1"), 12)
print("external_stats_test: " .. checks .. " checks passed")
