return {
    { id = "total_kills", label = "row_total_kills", section = "combat" },
    { id = "lesser_enemies_killed", label = "row_lesser_enemies_killed", section = "combat" },
    { id = "specials_killed", label = "row_specials_killed", section = "combat" },
    { id = "elites_killed", label = "row_elites_killed", section = "combat" },
    { id = "companion_kills", label = "row_companion_kills", section = "combat" },
    { id = "damage_dealt", label = "row_damage_dealt", section = "combat" },
    { id = "melee_damage", label = "row_melee_damage", section = "combat" },
    { id = "ranged_damage", label = "row_ranged_damage", section = "combat" },
    { id = "other_damage", label = "row_other_damage", section = "combat" },
    { id = "dot_damage", label = "row_dot_damage", section = "combat" },
    { id = "companion_damage", label = "row_companion_damage", section = "combat" },
    { id = "damage_to_bosses", label = "row_damage_to_bosses", section = "combat" },
    { id = "headshots", label = "row_headshots", section = "combat" },
    { id = "critical_hits", label = "row_critical_hits", section = "combat" },
    { id = "enemies_staggered", label = "row_enemies_staggered", section = "combat" },
    { id = "debuffs_applied", label = "row_debuffs_applied", section = "combat" },
    { id = "damage_taken", label = "row_damage_taken", section = "survival" },
    { id = "downs_and_deaths", label = "row_downs_and_deaths", section = "survival" },
    { id = "times_disabled", label = "row_times_disabled", section = "survival" },
    { id = "healthstation_uses", label = "row_healthstation_uses", section = "survival" },
    { id = "ammo_pickups", label = "row_ammo_pickups", section = "survival" },
    { id = "ammo_collected", label = "row_ammo_collected", section = "survival" },
    { id = "combat_ability_uses", label = "row_combat_ability_uses", section = "survival" },
    { id = "enemies_aggroed", label = "row_enemies_aggroed", section = "survival" },
    { id = "coherency_uptime", label = "row_coherency_uptime", section = "survival" },
}
