local mod = get_mod("AnotherScoreboard")
local enemies = mod:io_dofile("AnotherScoreboard/scripts/mods/AnotherScoreboard/AnotherScoreboard_enemies")

local localization = {
    external_details_key = { en = "External stat details (Tab scoreboard)" },
    external_details_key_description = { en = "Toggle all collapsible external stat groups in the in-mission Tab scoreboard. End screens and history use clickable group headings." },
    loadout_title = { en = "Squad Loadouts" },
    loadout_equipment = { en = "Weapons & Signature Talents" },
    loadout_tree = { en = "Talent Tree" },
    loadout_readonly = { en = "MISSION SNAPSHOT  /  READ ONLY" },
    loadout_missing = { en = "No loadout was recorded for this player.\nLoadouts are saved with new mission results." },
    loadout_no_weapon = { en = "Weapon not recorded" },
    loadout_no_selection = { en = "None recorded" },
    loadout_no_description = { en = "No description available." },
    loadout_perks = { en = "PERKS" },
    loadout_blessings = { en = "BLESSINGS" },
    loadout_stats = { en = "BASE RATING" },
    loadout_expertise = { en = "EXPERTISE" },
    loadout_blitz = { en = "Blitz" },
    loadout_aura = { en = "Aura" },
    loadout_ability = { en = "Combat Ability" },
    loadout_keystone = { en = "Keystone" },
    loadout_tree_missing = { en = "No compatible talent tree was recorded for this player." },
    loadout_tree_changed = { en = "The game's talent tree has changed since this mission.\nThe saved build cannot be displayed on the current tree." },
    loadout_rank = { en = "RANK" },
    loadout_specialization = { en = "Specialization" },
    loadout_hint_open = { en = "[U] Loadouts  |  [Click player] Social" },
    loadout_hover_scroll = { en = "Mouse wheel: previous / next description page" },
    loadout_hint_equipment = { en = "[U / Esc] Back  |  [1-4 / Wheel] Player  |  [T] Tree  |  [Hover talent] Description  |  [Click player] Social" },
    loadout_hint_tree = { en = "[U / Esc] Back  |  [1-4] Player  |  [T] Weapons  |  [Wheel] Zoom  |  [Left drag] Pan  |  [Hover] Details" },
	mod_name        = { en = "Another Scoreboard" },
	mod_description = { en = "Performance-focused end-of-mission and in-mission scoreboard." },
	open_scoreboard_history = { en = "Open Scoreboard History" },
	open_scoreboard_history_tooltip = { en = "Open the latest saved Another Scoreboard results." },
	scoreboard_theme_header = { en = "Scoreboard Appearance" },
	scoreboard_theme_header_tooltip = { en = "Customize the full scoreboard's theme, text scale, and row shading." },
	scoreboard_theme = { en = "Theme" },
	scoreboard_theme_tooltip = { en = "Applies to the full scoreboard, Scoreboard History, Live Stats, and Boss Popup." },
	scoreboard_theme_default = { en = "Default" },
	scoreboard_theme_reject_olive = { en = "Reject Olive" },
	scoreboard_theme_inquisition_navy = { en = "Inquisition Navy" },
	scoreboard_theme_manufactorum_slate = { en = "Manufactorum Slate" },
	scoreboard_theme_void_purple = { en = "Void Purple" },
	scoreboard_theme_high_contrast_obsidian = { en = "High Contrast Obsidian" },

	show_at_end                = { en = "Show at Mission End" },
	show_at_end_tooltip        = { en = "Open automatically when the mission ends." },
	show_in_mission            = { en = "Show In Mission" },
	show_in_mission_tooltip    = { en = "Show in the tactical overlay during missions." },
	tab_scoreboard_header      = { en = "In-Mission Scoreboard (Tab)" },
	tab_scoreboard_header_tooltip = { en = "Settings for the full scoreboard shown with Tab during a mission." },
	scoreboard_scale           = { en = "Scale" },
	scoreboard_scale_tooltip   = { en = "In-mission Tab scoreboard size in percent." },
	scoreboard_text_scale      = { en = "Text Scale" },
	scoreboard_text_scale_tooltip = { en = "Text size for full Tab, end-of-mission, and opened History scoreboards. Text is reduced locally when needed to keep it on one line." },
	local_player_first         = { en = "Always Show Your Stats to the Left" },
	local_player_first_tooltip = { en = "Show your player column first in full scoreboards." },
	alternating_row_shading    = { en = "Alternating Row Shading" },
	alternating_row_shading_tooltip = { en = "Use fixed shading for headings and alternating shading for detail rows in full scoreboards." },
	scoreboard_opacity         = { en = "Opacity" },
	scoreboard_opacity_tooltip = { en = "In-mission Tab scoreboard opacity. 0 = transparent, 255 = opaque." },
	vertical_offset            = { en = "Vertical Offset" },
	vertical_offset_tooltip    = { en = "Move the in-mission Tab scoreboard vertically. Positive values move it up." },
	horizontal_offset          = { en = "Horizontal Offset" },
	horizontal_offset_tooltip  = { en = "Move the in-mission Tab scoreboard horizontally. Positive values move it right." },
	end_scoreboard_header      = { en = "End-of-Mission Scoreboard" },
	end_scoreboard_header_tooltip = { en = "Settings for the scoreboard shown on the mission ending screen." },
	end_scoreboard_scale       = { en = "Scale" },
	end_scoreboard_scale_tooltip = { en = "End-of-mission scoreboard size in percent." },
	end_scoreboard_opacity     = { en = "Opacity" },
	end_scoreboard_opacity_tooltip = { en = "End-of-mission scoreboard opacity. 0 = transparent, 255 = opaque." },
	end_scoreboard_vertical_offset = { en = "Vertical Offset" },
	end_scoreboard_vertical_offset_tooltip = { en = "Move the end-of-mission scoreboard vertically. Positive values move it up." },
	end_scoreboard_horizontal_offset = { en = "Horizontal Offset" },
	end_scoreboard_horizontal_offset_tooltip = { en = "Move the end-of-mission scoreboard horizontally. Positive values move it right." },
	live_scoreboard_header     = { en = "Live Stats HUD" },
	live_scoreboard_header_tooltip = { en = "Settings for the live mission HUD scoreboard." },
	show_live_scoreboard       = { en = "Show Live Scoreboard" },
	show_live_scoreboard_tooltip = { en = "Show a live HUD box with selected mission stats." },
	live_scoreboard_archetype = { en = "Class" },
	live_scoreboard_archetype_tooltip = { en = "Choose which class's Live Stats settings to edit." },
	live_scoreboard_stat_count = { en = "Number of Live Stats" },
	live_scoreboard_stat_count_tooltip = { en = "Choose how many Live Stats columns to show for this class." },
	live_scoreboard_stat_count_1 = { en = "1" },
	live_scoreboard_stat_count_2 = { en = "2" },
	live_scoreboard_stat_count_3 = { en = "3" },
	live_scoreboard_stat_1 = { en = "Live Stat 1 (Sort Players By)" },
	live_scoreboard_stat_2 = { en = "Live Stat 2" },
	live_scoreboard_stat_3 = { en = "Live Stat 3" },
	live_scoreboard_stat_tooltip = { en = "Choose this Live Stats column. Selecting a stat already in use swaps the two columns." },
	live_stat_damage = { en = "Damage" },
	live_stat_kills = { en = "Kills" },
	live_stat_hp_lost = { en = "HP Lost" },
	live_stat_specials = { en = "Specials killed" },
	live_stat_elites = { en = "Elites killed" },
	live_stat_ranged_elites = { en = "Ranged Elites killed" },
	live_stat_melee_elites = { en = "Melee Elites killed" },
	live_stat_companion_kills = { en = "Companion kills" },
	live_stat_critical_hits = { en = "Critical hits" },
	live_stat_critical_ratio = { en = "Critical hit ratio" },
	live_stat_weakspots = { en = "Weakspots" },
	live_stat_weakspot_ratio = { en = "Weakspot hit ratio" },
	live_stat_boss_damage = { en = "Boss Damage" },
	live_stat_coherency = { en = "Coherency" },
	live_stat_melee_damage = { en = "Melee damage" },
	live_stat_ranged_damage = { en = "Ranged damage" },
	live_stat_dot_damage = { en = "Damage over time" },
	live_stat_bleeding_damage = { en = "Bleeding damage" },
	live_stat_soulblaze_damage = { en = "Soulblaze damage" },
	live_stat_burning_damage = { en = "Burning damage" },
	live_stat_toxin_damage = { en = "Toxin damage" },
	live_stat_companion_damage = { en = "Companion damage" },
	live_stat_enemies_staggered = { en = "Enemies staggered" },
	live_stat_debuffs_applied = { en = "Debuffs applied" },
	live_stat_downs_deaths = { en = "Downs & Deaths" },
	live_stat_downs = { en = "Downs" },
	live_stat_deaths = { en = "Deaths" },
	live_stat_revives_rescues = { en = "Revives & Rescues" },
	live_stat_disabled = { en = "Disabled" },
	live_stat_disabled_helped = { en = "Disabled helped" },
	live_stat_medicae_uses = { en = "Medicae uses" },
	live_stat_ammo_pickups = { en = "Ammo pickups" },
	live_stat_ammo_gained = { en = "Ammo gained" },
	live_stat_ability_uses = { en = "Ability uses" },
	live_stat_enemies_aggroed = { en = "Enemies Aggro'd" },
	live_scoreboard_scale      = { en = "Scale" },
	live_scoreboard_scale_tooltip = { en = "Live scoreboard size in percent." },
	live_scoreboard_x_offset   = { en = "Horizontal Offset" },
	live_scoreboard_x_offset_tooltip = { en = "Move the live scoreboard horizontally. Positive values move it right." },
	live_scoreboard_y_offset   = { en = "Vertical Offset" },
	live_scoreboard_y_offset_tooltip = { en = "Move the live scoreboard vertically. Positive values move it up." },
	live_scoreboard_bg_opacity      = { en = "Background Opacity" },
	live_scoreboard_bg_opacity_tooltip = { en = "Live scoreboard background opacity. 0 = transparent, 255 = opaque." },
	live_scoreboard_title      = { en = "Live Stats" },
	live_scoreboard_player     = { en = "Player" },
	live_header_damage         = { en = "Damage" },
	live_header_kills          = { en = "Kills" },
	live_header_hp_lost        = { en = "HP Lost" },
	live_header_specials       = { en = "Specials" },
	live_header_elites         = { en = "Elites" },
	live_header_ranged_elites  = { en = "Rng Elites" },
	live_header_melee_elites   = { en = "Melee Elites" },
	live_header_companion_kills = { en = "Comp Kills" },
	live_header_critical_hits  = { en = "Crits" },
	live_header_critical_ratio = { en = "Critical %%" },
	live_header_weakspots      = { en = "Weakspots" },
	live_header_weakspot_ratio = { en = "Weakspot %%" },
	live_header_boss_damage    = { en = "Boss Dmg" },
	live_header_coherency      = { en = "Coherency" },
	live_header_melee_damage   = { en = "Melee Dmg" },
	live_header_ranged_damage  = { en = "Ranged Dmg" },
	live_header_dot_damage     = { en = "DoT Dmg" },
	live_header_bleeding_damage = { en = "Bleeding" },
	live_header_soulblaze_damage = { en = "Soulblaze" },
	live_header_burning_damage = { en = "Burning" },
	live_header_toxin_damage   = { en = "Toxin" },
	live_header_companion_damage = { en = "Comp Dmg" },
	live_header_enemies_staggered = { en = "Staggered" },
	live_header_debuffs_applied = { en = "Debuffs" },
	live_header_downs_deaths   = { en = "Downs" },
	live_header_downs          = { en = "Downs" },
	live_header_deaths         = { en = "Deaths" },
	live_header_revives_rescues = { en = "Rev/Resc" },
	live_header_disabled       = { en = "Disabled" },
	live_header_disabled_helped = { en = "Dis. Help" },
	live_header_medicae_uses   = { en = "Medicae" },
	live_header_ammo_pickups   = { en = "Ammo P/U" },
	live_header_ammo_gained    = { en = "Ammo Gain" },
	live_header_ability_uses   = { en = "Ability Uses" },
	live_header_enemies_aggroed = { en = "Aggro'd" },
	show_boss_popup            = { en = "Show Boss Damage Popup" },
	show_boss_popup_tooltip    = { en = "Show a per-player boss damage popup when a boss dies." },
	show_boss_popup_damage     = { en = "Show Popup Damage" },
	show_boss_popup_damage_tooltip = { en = "Show each player's boss damage number in the boss popup." },
	show_boss_popup_percent    = { en = "Show Popup Percent" },
	show_boss_popup_percent_tooltip = { en = "Show each player's boss damage percentage in the boss popup." },
	show_boss_popup_total_damage = { en = "Show Total Boss Damage" },
	show_boss_popup_total_damage_tooltip = { en = "Show the total boss damage area at the bottom of the boss popup." },
	boss_popup_header          = { en = "Boss Damage Popup" },
	boss_popup_header_tooltip  = { en = "Settings for the boss damage popup." },
	boss_popup_scale           = { en = "Scale" },
	boss_popup_scale_tooltip   = { en = "Boss popup size in percent." },
	boss_popup_duration        = { en = "Duration (seconds)" },
	boss_popup_duration_tooltip = { en = "How long the boss popup stays visible, in seconds." },
	boss_popup_x_offset        = { en = "Horizontal Offset" },
	boss_popup_x_offset_tooltip = { en = "Move the boss popup horizontally. Positive values move it right." },
	boss_popup_y_offset        = { en = "Vertical Offset" },
	boss_popup_y_offset_tooltip = { en = "Move the boss popup vertically. Positive values move it up." },
	boss_popup_bg_opacity      = { en = "Background Opacity" },
	boss_popup_bg_opacity_tooltip = { en = "Boss popup background opacity. 0 = transparent, 255 = opaque." },
	scoreboard_stats_header    = { en = "Toggle Stats in Scoreboard" },
	scoreboard_stats_header_tooltip = { en = "Choose which tracked stats are visible in the full scoreboard views." },
	scoreboard_stats_combat_header = { en = "Combat Stats" },
	scoreboard_stats_survival_header = { en = "Survival Stats" },
	scoreboard_stats_group_tooltip = { en = "Visibility settings only. All stats continue to be tracked and saved." },
	scoreboard_stat_visibility_tooltip = { en = "Show this stat in the Tab, end-of-mission, and Scoreboard History views. Tracking and saved data are unaffected." },
	show_scoreboard_weakspot_percentage = { en = "Show Weakspot hit percentage" },
	show_scoreboard_critical_percentage = { en = "Show Critical hit percentage" },
	scoreboard_hit_percentage_tooltip = { en = "Show the percentage of valid melee and ranged hits beside each player's hit count." },

	cat_combat      = { en = "COMBAT" },
	cat_damage      = { en = "DAMAGE" },
	cat_boss        = { en = "BOSS" },
	cat_survival    = { en = "SURVIVAL" },
	cat_performance = { en = "PERFORMANCE" },

	row_total_kills            = { en = "Total kills" },
	row_lesser_enemies_killed  = { en = "Lesser Enemies" },
	row_ranged_lesser_enemies_killed = { en = "Ranged Lesser Enemies" },
	row_melee_lesser_enemies_killed = { en = "Melee Lesser Enemies" },
	row_specials_killed        = { en = "Specials" },
	row_elites_killed          = { en = "Elites" },
	row_ranged_elites_killed   = { en = "Ranged Elites" },
	row_melee_elites_killed    = { en = "Melee Elites" },
	row_companion_kills        = { en = "Companion kills" },

	row_damage_dealt           = { en = "Total damage" },
	row_melee_damage           = { en = "Melee damage" },
	row_ranged_damage          = { en = "Ranged damage" },
	row_other_damage           = { en = "Other damage" },
	row_damage_details         = { en = "Damage details" },
	row_dot_damage             = { en = "Damage over time" },
	row_dot_bleeding_damage    = { en = "Bleeding" },
	row_dot_soulblaze_damage   = { en = "Soulblaze" },
	row_dot_burning_damage     = { en = "Burning" },
	row_dot_toxin_damage       = { en = "Toxin" },
	row_companion_damage       = { en = "Companion damage" },
	row_damage_to_bosses       = { en = "Boss damage" },
	row_boss_beast_of_nurgle   = { en = "Beast of Nurgle" },
	row_boss_daemonhost        = { en = "Daemonhost" },
	row_boss_chaos_spawn       = { en = "Chaos Spawn" },
	row_boss_plague_ogryn      = { en = "Plague Ogryn" },
	row_boss_captain           = { en = "Captain" },
	row_boss_scab_captain      = { en = "Scab Captain" },
	row_boss_dreg_captain      = { en = "Dreg Captain" },
	row_boss_hexbound_daemonhost = { en = "Hexbound Daemonhost" },
	row_boss_ogryn_houndmaster = { en = "Pack Master" },
	row_boss_twins             = { en = "Twins" },
	row_utility                = { en = "Utility" },

	row_headshots              = { en = "Weakspot hits" },
	row_critical_hits          = { en = "Critical hits" },
	row_enemies_staggered      = { en = "Enemies staggered" },
	row_debuffs_applied        = { en = "Debuffs applied" },
	row_weighted_stagger       = { en = "Weighted stagger" },
	row_combat_ability_uses    = { en = "Ability uses" },
	row_enemies_aggroed        = { en = "Enemies Aggro'd" },
	row_coherency_uptime       = { en = "Coherency" },

	row_survivability        = { en = "Survivability" },
	row_damage_taken           = { en = "HP Lost" },
	row_downs_and_deaths       = { en = "Downs & Deaths" },
	row_downs                  = { en = "Downs" },
	row_deaths                 = { en = "Deaths" },
	row_revives_and_rescues    = { en = "Revives & Rescues" },
	row_times_disabled         = { en = "Disabled" },
	row_disabled_helped        = { en = "Disabled helped" },
	row_healthstation_uses     = { en = "Medicae uses" },
	row_combat_ability_uses_per_minute = { en = "Uses per minute" },
	row_combat_ability_average_time = { en = "Avg between uses" },
	row_ammo_pickups           = { en = "Ammo pickups" },
	row_ammo_collected         = { en = "Ammo gained" },

	loc_another_scoreboard_view_display_name = { en = "Scoreboard" },
	scoreboard_mission_time = { en = "Mission time" },
	loc_another_scoreboard_history_view_display_name = { en = "Scoreboard History" },
	history_view_title = { en = "Scoreboard History" },
	history_view_subtitle = { en = "Latest 10 completed missions" },
	history_saved_subtitle = { en = "Missions saved for later" },
	history_tab_recent = { en = "Recent" },
	history_tab_saved = { en = "Saved" },
	history_save = { en = "SAVE" },
	history_saved = { en = "SAVED" },
	history_manage = { en = "MANAGE" },
	history_name_popup_title = { en = "Name Saved Game" },
	history_name_popup_description = { en = "Enter an optional name. Leave it blank to use the generated mission title." },
	history_manage_popup_title = { en = "Manage Saved Game" },
	history_manage_current_name = { en = "Current name" },
	history_manage_generated_name = { en = "Generated mission title" },
	history_save_name = { en = "SAVE NAME" },
	history_remove = { en = "REMOVE" },
	history_cancel = { en = "CANCEL" },
	history_no_saved_entries = { en = "No saved games yet." },
	history_loading = { en = "Loading saved scoreboards..." },
	history_no_entries = { en = "No saved scoreboards yet." },
	history_game_type_expedition = { en = "Expedition" },
	history_game_type_mortis_trials = { en = "Mortis Trials" },
	history_game_type_maelstrom = { en = "Maelstrom" },
	history_game_type_auric_maelstrom = { en = "Auric Maelstrom" },
	history_unknown_mission = { en = "Unknown Mission" },
	history_unknown_difficulty = { en = "Unknown Difficulty" },
	history_escape_hint = { en = "ESC - Exit  |  SPACE - Clear History" },
	history_saved_hint = { en = "ESC - Exit  |  Mouse wheel - Scroll  |  Manage saved games individually" },
	history_scoreboard_back_hint = { en = "ESC - Back to Mission History" },
	scoreboard_default_hint = { en = "E - Specials/Elites  |  R - DoT types  |  T - Boss types" },
	scoreboard_enemy_hint = { en = "E - Hide Specials/Elite kills  |  R - DoT types  |  T - Boss types" },
	scoreboard_dot_hint = { en = "E - Specials/Elites  |  R - Hide DoT types  |  T - Boss types" },
	scoreboard_boss_hint = { en = "E - Specials/Elites  |  R - DoT types  |  T - Hide boss types" },
	history_scoreboard_default_hint = { en = "ESC - Back  |  E - Specials/Elites  |  R - DoT types  |  T - Boss types" },
	history_scoreboard_enemy_hint = { en = "ESC - Back  |  E - Hide Specials/Elite kills  |  R - DoT types  |  T - Boss types" },
	history_scoreboard_dot_hint = { en = "ESC - Back  |  E - Specials/Elites  |  R - Hide DoT types  |  T - Boss types" },
	history_scoreboard_boss_hint = { en = "ESC - Back  |  E - Specials/Elites  |  R - DoT types  |  T - Hide boss types" },
	scoreboard_hint_back = { en = "ESC - Back" },
	scoreboard_hint_specials_elites = { en = "E - Specials/Elites" },
	scoreboard_hint_hide_specials_elites = { en = "E - Hide Specials/Elites" },
	scoreboard_hint_enemy_details = { en = "E - Enemy Details" },
	scoreboard_hint_hide_enemy_details = { en = "E - Hide Enemy Details" },
	scoreboard_hint_specials = { en = "E - Specials" },
	scoreboard_hint_hide_specials = { en = "E - Hide Specials" },
	scoreboard_hint_elites = { en = "E - Elites" },
	scoreboard_hint_hide_elites = { en = "E - Hide Elites" },
	scoreboard_hint_dot = { en = "R - DoT types" },
	scoreboard_hint_hide_dot = { en = "R - Hide DoT types" },
	scoreboard_hint_boss = { en = "T - Boss types" },
	scoreboard_hint_hide_boss = { en = "T - Hide boss types" },
	scoreboard_hint_survival_details = { en = "Y - Survival details" },
	scoreboard_hint_hide_survival_details = { en = "Y - Hide Survival details" },
	scoreboard_hint_downs_deaths = { en = "Y - Survival details" },
	scoreboard_hint_hide_downs_deaths = { en = "Y - Hide Survival details" },
	scoreboard_hint_ability_rate = { en = "Y - Survival details" },
	scoreboard_hint_hide_ability_rate = { en = "Y - Hide Survival details" },
	scoreboard_hint_temporarily_hide = { en = "TAB + Q - Hide Scoreboard" },
	scoreboard_hint_end_hide = { en = "Q - Hide Scoreboard" },
	scoreboard_hint_end_show = { en = "Q - Show Scoreboard" },
}

for _, category in ipairs({ "specials", "elites" }) do
	for _, enemy in ipairs(enemies[category]) do
		localization[enemy.label] = { en = enemy.name }
	end
end

return localization
