return {
    { key = "damage", stat_id = "_total_damage", option = "live_stat_damage", header = "live_header_damage", format = "short" },
    { key = "kills", stat_id = "total_kills", option = "live_stat_kills", header = "live_header_kills", format = "count" },
    { key = "hp_lost", stat_id = "damage_taken", option = "live_stat_hp_lost", header = "live_header_hp_lost", format = "short", lower_better = true },
    { key = "specials", stat_id = "specials_killed", option = "live_stat_specials", header = "live_header_specials", format = "count" },
    { key = "elites", stat_id = "elites_killed", option = "live_stat_elites", header = "live_header_elites", format = "count" },
    { key = "ranged_elites", stat_id = "ranged_elites_killed", option = "live_stat_ranged_elites", header = "live_header_ranged_elites", format = "count" },
    { key = "melee_elites", stat_id = "melee_elites_killed", option = "live_stat_melee_elites", header = "live_header_melee_elites", format = "count" },
    { key = "companion_kills", stat_id = "companion_kills", option = "live_stat_companion_kills", header = "live_header_companion_kills", format = "count" },
    { key = "critical_hits", stat_id = "critical_hits", option = "live_stat_critical_hits", header = "live_header_critical_hits", format = "count" },
    { key = "critical_ratio", numerator_stat_id = "critical_ratio_hits", denominator_stat_id = "melee_ranged_hits", option = "live_stat_critical_ratio", header = "live_header_critical_ratio", format = "percent" },
    { key = "weakspots", stat_id = "headshots", option = "live_stat_weakspots", header = "live_header_weakspots", format = "count" },
    { key = "weakspot_ratio", numerator_stat_id = "weakspot_ratio_hits", denominator_stat_id = "melee_ranged_hits", option = "live_stat_weakspot_ratio", header = "live_header_weakspot_ratio", format = "percent" },
    { key = "boss_damage", stat_id = "damage_to_bosses", option = "live_stat_boss_damage", header = "live_header_boss_damage", format = "short" },
    { key = "coherency", option = "live_stat_coherency", header = "live_header_coherency", format = "percent" },
    { key = "melee_damage", stat_id = "melee_damage", option = "live_stat_melee_damage", header = "live_header_melee_damage", format = "short" },
    { key = "ranged_damage", stat_id = "ranged_damage", option = "live_stat_ranged_damage", header = "live_header_ranged_damage", format = "short" },
    { key = "dot_damage", stat_id = "dot_damage", option = "live_stat_dot_damage", header = "live_header_dot_damage", format = "short" },
    { key = "bleeding_damage", stat_id = "dot_bleeding_damage", option = "live_stat_bleeding_damage", header = "live_header_bleeding_damage", format = "short" },
    { key = "soulblaze_damage", stat_id = "dot_soulblaze_damage", option = "live_stat_soulblaze_damage", header = "live_header_soulblaze_damage", format = "short" },
    { key = "burning_damage", stat_id = "dot_burning_damage", option = "live_stat_burning_damage", header = "live_header_burning_damage", format = "short" },
    { key = "toxin_damage", stat_id = "dot_toxin_damage", option = "live_stat_toxin_damage", header = "live_header_toxin_damage", format = "short" },
    { key = "companion_damage", stat_id = "companion_damage", option = "live_stat_companion_damage", header = "live_header_companion_damage", format = "short" },
    { key = "enemies_staggered", stat_id = "enemies_staggered", option = "live_stat_enemies_staggered", header = "live_header_enemies_staggered", format = "count" },
    { key = "debuffs_applied", stat_id = "debuffs_applied", option = "live_stat_debuffs_applied", header = "live_header_debuffs_applied", format = "count" },
    { key = "downs_deaths", stat_id = "downs_and_deaths", option = "live_stat_downs_deaths", header = "live_header_downs_deaths", format = "count", lower_better = true },
    { key = "downs", stat_id = "downs", option = "live_stat_downs", header = "live_header_downs", format = "count", lower_better = true },
    { key = "deaths", stat_id = "deaths", option = "live_stat_deaths", header = "live_header_deaths", format = "count", lower_better = true },
    { key = "revives_rescues", stat_id = "revives_and_rescues", option = "live_stat_revives_rescues", header = "live_header_revives_rescues", format = "count" },
    { key = "disabled", stat_id = "times_disabled", option = "live_stat_disabled", header = "live_header_disabled", format = "count", lower_better = true },
    { key = "disabled_helped", stat_id = "disabled_helped", option = "live_stat_disabled_helped", header = "live_header_disabled_helped", format = "count" },
    { key = "medicae_uses", stat_id = "healthstation_uses", option = "live_stat_medicae_uses", header = "live_header_medicae_uses", format = "count", lower_better = true },
    { key = "ammo_pickups", stat_id = "ammo_pickups", option = "live_stat_ammo_pickups", header = "live_header_ammo_pickups", format = "count" },
    { key = "ammo_gained", stat_id = "ammo_collected", option = "live_stat_ammo_gained", header = "live_header_ammo_gained", format = "count" },
    { key = "ability_uses", stat_id = "combat_ability_uses", option = "live_stat_ability_uses", header = "live_header_ability_uses", format = "count" },
    { key = "enemies_aggroed", stat_id = "enemies_aggroed", option = "live_stat_enemies_aggroed", header = "live_header_enemies_aggroed", format = "count" },
}
